version: '3'

networks:
  refibra-network:
    driver: bridge

services:
  refibra-angular:
    container_name: refibra-angular
    hostname: refibraangular
    build: .
    ports:
      - '4201:4201'
    environment:
        BACKEND_API_FUSEKI_URL: "http://refibra-api:5000"
    networks:
        - refibra-network