version: '3'

networks:
  refibra-network:
    driver: bridge

services:
  refibra-angular:
    container_name: refibra-angular
    hostname: refibraangular
    build: 
      context: .
      args:        
        BACKEND_API_FUSEKI_URL: "http://devcabral.com.br:5000"
        IMAGES_PATH: 'https://res.cloudinary.com/dixelsjzs/image/upload/v1565234304/Refibra/'
    ports:
      - '4201:4201'
    networks:
        - refibra-network